### ISSUE TITLE
Request: Add to HACS

### ISSUE THREAD

**Issue by JamieP83** [nitobuendia/oura-custom-component#1]
Hey,
would be great to have this available via HACS
https://hacs.xyz/

**Comment by tuomaskuittinen** [comment]
+1 for this!

**Comment by adrkable** [comment]
+1

**Comment by nitobuendia** [comment]
Happy to see that this is helpful. I will have a look at the [documentation for HACS for Custom Components](https://hacs.xyz/docs/publish/integration) and see how involved it is to add the support.

**Comment by nitobuendia** [comment]
I think all requirements are now ready. The only missing requirement is to transfer it to HACS [custom-components](https://github.com/custom-components) or [hacs default](https://github.com/hacs/default) as [per this guide](https://hacs.xyz/docs/publish/include).

I have sent the [pull request](https://github.com/hacs/default/pull/466) to add to default.

I am unclear whether repository also needs to be transferred to the custom-components. However, I do not have permissions to do so.

**Comment by nitobuendia** [comment]
Added to [wheels-custom-integrations](https://github.com/home-assistant/wheels-custom-integrations) ([PR#65](https://github.com/home-assistant/wheels-custom-integrations/pull/65)).

**Comment by nitobuendia** [comment]
Created [PR for Brand logos](https://github.com/home-assistant/brands/pull/1646).

**Comment by nitobuendia** [comment]
Wheels was not needed since there were no requirements. Indeed, the only requirement is `requests` which is already existing in Home-Assistant.

**Comment by nitobuendia** [comment]
The [request to add to HACS](https://github.com/hacs/default/pull/466) seems approved.

@JamieP83 @tuomaskuittinen @adrkable If you could verify that you can see it on HACS in a few hours or days, I would appreciate it :) (Not sure what the normal ETA is).

**Comment by tuomaskuittinen** [comment]
@nitobuendia I was able to find and install this with HACS, thanks! I had installed this previously manually and now removed the custom_components/oura folder and installed with HACS. My "oura-token" file was left untouch and worked with HACS version like it worked before with manual installation, as expected.

However I run into problem that my "Configuration validation" did not finish and when running "core check" from the command line there was an error about "core integration not found". I did not try to restart my Home Assistant with error in the configs.

I was able to resolve this by removing "core" from manifest.json dependencies list and everything seems to work now.

**Comment by nitobuendia** [comment]
Thanks a lot for testing and installing, @tuomaskuittinen

**Comment by nitobuendia** [comment]
HACS support will be reverted until YAML (or equivalent non-UI configuration) becomes a supported mode for integrations ([reference](https://community.home-assistant.io/t/the-future-of-yaml/186879)).

**Comment by nitobuendia** [comment]
For those who are affected by the HACS decision, [sharing my personal views on the YAML issue](https://twitter.com/nitobuendia/status/1268866965264756736).

**Comment by nitobuendia** [comment]
Hi @JamieP83, everyone,

I will be closing this for now. I do not think there are short-term plans to include in HACS; and with issues like the ones reported [here](https://community.home-assistant.io/t/disclosure-security-vulnerabilities-in-custom-integrations-hacs-dwains-dashboard-font-awesome-and-others/271576) and [here](https://community.home-assistant.io/t/security-disclosure-2-vulnerabilities-in-custom-integrations-hacs-font-awesome-and-others/272049/5), I think that if you install a Custom Component, you should make a bit of due diligence on the code you add to the system first :)

**Comment by leikoilja** [comment]
@nitobuendia, do you think it's time to put aside the personal stride regarding YAML file configuration option and include the integration in HACS? :)
