### ISSUE TITLE
[Feature Request] Activity and Readiness

### ISSUE THREAD

**Issue by webosa** [nitobuendia/oura-custom-component#13]
Hi, thanks for the integration, this is pretty neat. 

I was wondering if you could include also Activity and Readiness data in to this. I am currently bringing some activity data from a "super hacky" Garmin integration which keeps breaking all the time, would be nice if I could get rid of that integration.

![person_card_j](https://user-images.githubusercontent.com/16862797/147383388-62fffa3b-4a2b-4cb2-8a06-1a685bbad237.png)

**Comment by nitobuendia** [comment]
Hi @webosa - thanks a lot for the feedback.

Yes, there are some discussions on this on #10. Would that address your concern? You can read on the data and thought process, although there's no current ongoing work for it. Closing it for now as I think it's a duplicate.

Thanks!
