### ISSUE TITLE
[Maintenance] Upgrade to Oura API v2

### ISSUE THREAD

**Issue by nitobuendia** [nitobuendia/oura-custom-component#15]
Oura has released [Oura API Version 2](https://api.ouraring.com/v2/docs). We would need to upgrade before the sunset of v1. This may also affect feature requests on #10 and #14 which might be best implemented in the new version directly to avoid double work.

**Comment by nitobuendia** [comment]
Sunset seems to be somewhen in 2023 (tbc). There's still time to upgrade. Migration guide is not up yet, we can wait for that for ease of migration.

**Comment by Yersi88** [comment]
I like the idea of switching to 2.0 API as the old one is not able to get all the data from Ring Gen3 such as 24/7 heartrate.

**Comment by nitobuendia** [comment]
Just checked and the v2 API does not support all features yet. In particular, the most critical endpoint on the current implementation is sleep. As of right now, [sleep data is not available on the v2 API](https://cloud.ouraring.com/v2/docs#tag/Daily-Sleep):

> Sleep period is a nearly continuous, longish period of time spent lying down in bed. Sleep is currently available in the V1 API. We plan to release sleep with the V2 API in the near future. [Click here for V1 API documentation](https://cloud.ouraring.com/docs/sleep).


Ideally, we should do the migration of Auth + Readiness + Sleep at once, so putting this off until all the endpoints are ready.

**Comment by guildencrantz** [comment]
Looks like everything's there now? Sleep no longer has the v1 link, nor do any of the other endpoints. I haven't validated.

**Comment by nitobuendia** [comment]
Yes, @guildencrantz - it looks like so. Thanks for being on top.

I will try to have a look, as I do intend to migrate to the new API. It may take a few weeks, though.

**Comment by nitobuendia** [comment]
This work has been started and more or less completed. It currently sits in an unpublished branch, but I should be releasing it in the next days and merging it once it is ready.

**Comment by nitobuendia** [comment]
This is now completed on branch [oura-v2](https://github.com/nitobuendia/oura-custom-component/tree/oura-v2). The code is still experimental and subject to change. It will be merged after adding other sensors (e.g. #10) and data points.

The new component requires a different configuration, so if you want to use it, you may want to completely reinstall it from scratch until it's ready.
