### ISSUE TITLE
device_state_attributes

### ISSUE THREAD

**Issue by MechEng70** [nitobuendia/oura-custom-component#17]
FYI - 

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:601
First occurred: 11:20:34 AM (1 occurrences)
Last logged: 11:20:34 AM

Entity sensor.sleep_quality (<class 'custom_components.oura.sensor.OuraSleepSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by nitobuendia** [comment]
@MechEng70 Jason, do you have the latest version as downloaded from this repository? This was fixed on a [recent commit](https://github.com/nitobuendia/oura-custom-component/commit/931985f4bc9f8eebe223bb2cfcad8f8362083bf3). I would suggest that you update the code manually.

**Comment by MechEng70** [comment]
I will check.  Thanks.
