### ISSUE TITLE
deprecated base_url component in api.py for home assistant v 0.114.0

### ISSUE THREAD

**Issue by tonfa80** [nitobuendia/oura-custom-component#2]
Is it possible to get component working with Home Assistant v 0.114.0, where `base_url` is deprecated?

Got this error to log every time when trying to get retrieve data:

```
2020-08-25 19:25:45 WARNING (SyncWorker_2) [homeassistant.components.http] Detected use of deprecated `base_url` property, use `homeassistant.helpers.network.get_url` method instead. Please report issue to the custom component author for oura using this method at custom_components/oura/api.py, line 236: base_url = self._sensor._hass.config.api.base_url
2020-08-25 19:25:45 ERROR (SyncWorker_2) [root] Oura API was unable to retrieve new API token.
2020-08-25 19:25:45 ERROR (SyncWorker_2) [root] Couldn't fetch data for Oura ring sensor
```

**Comment by nitobuendia** [comment]
Hi @tonfa80 Thanks for reporting.

As discussed in the community, the change itself is pretty straightforward ([article](https://developers.home-assistant.io/blog/2020/05/08/instance-url-helper/)). However, ideally we want to make this work on both old and new systems by creating some "catch all".

I may have some time soon to have a look, but if someone is faster, happy to review PRs too.

**Comment by nitobuendia** [comment]
I've scheduled sometime on the week of 14th September to fix this. Thanks for understanding.


In the meantime, feel free to fix yourself by changing uses of `hass.config.api.base_url` ([163](https://github.com/nitobuendia/oura-custom-component/blob/720078dbd373bc1ef561fedfcc7e9f8bbf18e412/custom_components/oura/api.py#L163), [236](https://github.com/nitobuendia/oura-custom-component/blob/720078dbd373bc1ef561fedfcc7e9f8bbf18e412/custom_components/oura/api.py#L236)) for `network.get_url(hass)`. It may require other variations (e.g. to make external), but I have not verified yet.


It also requires adding a new import:
```
from homeassistant.helpers import network
```

**Comment by nitobuendia** [comment]
@tonfa80 This should be fixed now. Let me know if you want to try it out :) Thanks again for reporting.

**Comment by tonfa80** [comment]
Hi,

@nitobuendia Thanks a lot.

I got it working now. I just needed to remove the existing application from Oura site and create it again.
