### ISSUE TITLE
Discontinuation of Oura API V1, support of additional V2 endpoints

### ISSUE THREAD

**Issue by sonmaximum** [nitobuendia/oura-custom-component#35]
I just wanted to let this project's maintainer know, Oura has announced that it is discontinuing its V1 API in Jan 2024, after which it will no longer be available.

It looks like, at minimum, this project is using the V1 bedtimes endpoint.  I believe this should be replaced with the V2 sleep times endpoint `/v2/usercollection/sleep_time`

There have been a few other new V2 endpoints implemented by Oura since this project was last updated.  I'm not sure whether they are relevant for this project, but the details can be found at https://cloud.ouraring.com/v2/docs

**Comment by nitobuendia** [comment]
Hi @sonmaximum - thanks for reporting. This project migrated to API v2 in Jan. You can track the changes on #15. There were other changes done later to add additional endpoints and information. You may need to edit your YAML to access those additional data points. Refer to the README on the [homepage of the project](https://github.com/nitobuendia/oura-custom-component) to see the latest configuration instructions.
