### ISSUE TITLE
Oura Gen3 - Subcription necessary for this project?

### ISSUE THREAD

**Issue by smartmatic** [nitobuendia/oura-custom-component#37]
Hi,
i am interested to buy an Oura Ring and found this project. But its not clear for me if i really need a subscription to get all available sensors from the API?

**Comment by nitobuendia** [comment]
Hi @smartmatic - that question is probably best addressed to Oura customer support. I am not affiliated with them in any way.

That being said, in my experience, the answer is unfortunately yes.
