### ISSUE TITLE
version and manifest update needed for latest home assistant version

### ISSUE THREAD

**Issue by Techknowledgeman** [nitobuendia/oura-custom-component#5]
No 'version' key in the manifest file for custom integration 'oura'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'oura'

**Comment by nitobuendia** [comment]
Thanks for reporting, @Techknowledgeman 

I didn't find documentation on this change. However, I think it's just asking to add `"version": "xxx"` to the manifest.json. I have added `"version": "1.0",` and this message is no longer appearing on my version.

**Comment by Techknowledgeman** [comment]
Yeah that's all that's needed. It was documented in the last two release notes.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
